### PR TITLE
Change DB name, clean tests, update email address for email service

### PR DESCRIPTION
**Pull request by DinuWije**
## Implementation description
* Change the DB Docker container name to SHOW-database
* In the env file, change the db name to show_db (and show_db_test)
* You will need to drop the database, docker compose down, delete all volumes, and the docker compose build again (details below)
* You will also need to update your env file

# Changes you need to make
* msg Dinu for the new env file details if you don't have them already
* Run the following commands:
```bash
docker compose down 
docker rm -f $(docker ps -a -q) # deletes all running/stopped containers
docker compose down --volumes # brings down all volumes (incl database)
docker volume rm $(docker volume ls -q) # deletes all docker volumes
docker-compose up --build
docker exec -it SHOW-backend /bin/bash -c "flask db upgrade"
```
Why delete docker volumes? Because it gets rid of persisted data (ie. database info) for a full reset of your system. You will need to re-register a new user because your old one is deleted.

## Checklist
- [x] My PR name is descriptive and in imperative tense
- [x] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [x] I have run the appropriate linter(s)
- [x] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

### CODE REVIEW

**Comment by safchow** [comment]
docker containers and database has been renamed correctly however, I'm noticing the backend is unresponsive (can't create a new user on front-end, postman requests running forever, e2e tests also running forever). Not sure if related to this pr. I've also made sure to use the 8080 port.

**Comment by safchow** [comment]
> docker containers and database has been renamed correctly however, I'm noticing the backend is unresponsive (can't create a new user on front-end, postman requests running forever, e2e tests also running forever). Not sure if related to this pr. I've also made sure to use the 8080 port.

re-tested: no issues, guess something on my end was breaking

**Review by safchow — APPROVED** [review]
demon :smiling_imp:

**Review by connor-bechthold — APPROVED** [review]
Works as expected!

**Pull request merged**
